### ISSUE TITLE
Soybean weight

### ISSUE THREAD

**Issue by danr** [nhynes/pbean#2]
_42 g soybeans; soaked_ is (for me) ambiguous, is it 42 grams before or after soaked?

I tried making this by just eyeballing the ingredients (I don't have a food scales), and it ended up tasting too much of soy bean.

**Comment by nhynes** [comment]
It's 42g dry which should be [just under a quarter cup](https://ndb.nal.usda.gov/ndb/foods/show/16108?fgcd=&manu=&format=&count=&max=25&offset=&sort=default&order=asc&qlookup=soybeans&ds=&qt=&qp=&qa=&qn=&q=&ing=), which is surprisingly less volume than one might think.

> it ended up tasting too much of soy bean
The soy flavor is definitely an acquired taste (you do stop noticing it after a while, though). The [original recipe](https://github.com/nhynes/pbean/tree/2787257ab57a37613b4401e9a24c8adec94b2e46) called for white beans, which have a milder flavor. Soy is just nice because it has more protein/kcal and leaves more room for pb and cocoa powder.

Thanks for trying!

**Comment by danr** [comment]
Ok! Thank you for the clarification ;)
